# Generated by Django 3.2 on 2022-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tags',
            field=models.ManyToManyField(to='api.Tag', verbose_name='标签'),
        ),
    ]
